<?php

/**
 * @file
 * Primary module hooks for Webform Summation Field module.
 */

/**
 * Implements hook_preprocess_webform_actions().
 *
 * @see template_preprocess_webform_actions()
 */
function grants_webform_actions_alter_preprocess_webform_actions(array &$variables) {
  $variables['draft']['#attributes']['class'][] = 'hds-button--supplementary';
  $variables['element']['draft']['#attributes']['class'][] = 'hds-button--supplementary';
}
