<?php

/**
 * @file
 * Primary module hooks for Webform Summation Field module.
 */

/**
 * Implements hook_theme().
 */
function grants_webform_summation_field_theme() {
  $info = [
    'grants_webform_summation_field' => [
      'render element' => 'element',
    ],
  ];

  return $info;
}

/**
 * Implements hook_page_attachments().
 */
function grants_webform_summation_field_page_attachments(array &$page) {

}
