*** Variables ***
${TUNNISTAMO_HETU}                              090797-999P
${TUNNISTAMO_COMPANY_ID}                        7009741-8
${TUNNISTAMO_COMPANY_NAME}                      Lachael Testifirma OY
${TUNNISTAMO_PERSON_NAME}                       Roger Weberman

${SITE_NAME}                                    Helsingin kaupunki
${SITE_NAME_ALT}                                Avustusasiointi

${INPUT_EMAIL}                                  testi@test.fi
${INPUT_CONTACT_PERSON}                         Testi Henkilö
${INPUT_CONTACT_PERSON_PHONE_NUMBER}            040 123 123
${INPUT_COMMUNITY_ADDRESS_INDEX}                1
${INPUT_BANK_ACCOUNT_NUMBER}                    FI4069674615287672
${INPUT_SUBVENTION_AMOUNT}                      123
${INPUT_SUBVENTION_AMOUNT_FORMATTED}            123,00€
${INPUT_SUBVENTION_AMOUNT_FORMATTED_ALT}        123€
${INPUT_COMPENSATION_PURPOSE}                   Tässä on lyhyt kuvaus
${INPUT_COMPENSATION_EXPLANATION}               Selitys edellisestä avustuksesta
${INPUT_FEE_PERSON}                             6789
${INPUT_FEE_PERSON_FORMATTED}                   6 789,00€
${INPUT_PRIMARY_ART}                            Museo

${INPUT_CULTURE_PROJECT_NAME}                   Kulttuurihanke 1
${INPUT_CULTURE_PROJECT_DESC}                   Tämä on robotilla tehty hakemus.
${INPUT_CULTURE_PROJECT_PREMISE_NAME}           Robottitila
${INPUT_CULTURE_PROJECT_PREMISE_POSTCODE}       00100
${INPUT_CULTURE_PROJECT_START}                  1.6.2024
${INPUT_CULTURE_PROJECT_END}                    5.6.2024
${INPUT_CULTURE_PROJECT_SPONSOR}                4567
${INPUT_CULTURE_DAYS_IN_HKI}                    12

${INPUT_TEMP_BANK_ACCOUNT_NUMBER}               FI20 7527 9645 7216 23
${INPUT_TEMP_ADDRESS}                           Robottikatu 999
${INPUT_TEMP_PHONE}                             +358409999999
${INPUT_TEMP_EMAIL}                             robotti-temp@hel.fi
${INPUT_TEMP_WEBSITE}                           https://robotti-temp.fi
${INPUT_TEMP_COMPANY_NAME}                      Robottitestaus Ky
