*** Variables ***
${TUNNISTAMO_HETU}                    210281-9988
${TUNNISTAMO_COMPANY_ID}              2036583-2
${TUNNISTAMO_COMPANY_NAME}            Maanrakennus Ari Eerola T:mi
${TUNNISTAMO_PERSON_NAME}             Nordea Demo
${SITE_NAME}                          Helsingin kaupunki
${SITE_NAME_ALT}                      Avustusasiointi
${APPLICATION_TITLE}                  Kaupunginhallituksen yleisavustushakemus
${APPLICATION_TITLE_ALT}              Kaupunginhallitus, yleisavustus
${INPUT_EMAIL}                        testi@test.fi
${INPUT_CONTACT_PERSON}               Testi Henkilö
${INPUT_CONTACT_PERSON_PHONE_NUMBER}  040 123 123
${INPUT_COMMUNITY_ADDRESS_INDEX}      1
${INPUT_BANK_ACCOUNT_NUMBER}          FI83444 349489 88724
${INPUT_SUBVENTION_AMOUNT}            123
${INPUT_SUBVENTION_AMOUNT_FORMATTED}  123,00€
${INPUT_SUBVENTION_AMOUNT_FORMATTED_ALT}  123€
${INPUT_COMPENSATION_PURPOSE}         Tässä on lyhyt kuvaus
${INPUT_COMPENSATION_EXPLANATION}     Selitys edellisestä avustuksesta
${INPUT_FEE_PERSON}                   6789
${INPUT_FEE_PERSON_FORMATTED}         6 789,00€
${INPUT_PRIMARY_ART}                  Museo
${INPUT_CULTURE_PROJECT_NAME}         Kulttuurihanke 1
${INPUT_CULTURE_PROJECT_DESC}         Tämä on robotilla tehty hakemus.
${INPUT_CULTURE_PROJECT_PREMISE_NAME}   Robottitila
${INPUT_CULTURE_PROJECT_PREMISE_POSTCODE}      00100
${INPUT_CULTURE_PROJECT_START}        1.6.2024
${INPUT_CULTURE_PROJECT_END}          5.6.2024
${INPUT_CULTURE_PROJECT_SPONSOR}      4567
${INPUT_CULTURE_DAYS_IN_HKI}          12
${INPUT_TEMP_BANK_ACCOUNT_NUMBER}     FI20 7527 9645 7216 23
${INPUT_TEMP_ADDRESS}                 Robottikatu 123
${INPUT_TEMP_PHONE}                   +358409999999
${INPUT_TEMP_EMAIL}                   robotti@hel.fi
${INPUT_TEMP_WEBSITE}                 https://robotti.fi
${INPUT_TEMP_COMPANY_NAME}            Robottitestaus Ky
