*** Variables ***
${TUNNISTAMO_HETU}                    210281-9988
${TUNNISTAMO_COMPANY_ID}              7769480-5
${SITE_NAME}                          Helsingin kaupunki
${SITE_NAME_ALT}                      Hel.fi Avustusasiointi
${YA_APPLICATION_TITLE}                  Kaupunginhallituksen yleisavustushakemus
${YA_APPLICATION_TITLE_ALT}              Kaupunginhallitus, yleisavustus
${INPUT_EMAIL}                        testi@test.fi
${INPUT_CONTACT_PERSON}               Testi Henkilö
${INPUT_CONTACT_PERSON_PHONE_NUMBER}  040 123 123
${INPUT_COMMUNITY_ADDRESS_INDEX}      1
${INPUT_BANK_ACCOUNT_NUMBER}          FI49 5000 9420 0287 30
${INPUT_TEMP_BANK_ACCOUNT_NUMBER}     FI20 7527 9645 7216 23
${INPUT_SUBVENTION_AMOUNT}            123
${INPUT_SUBVENTION_AMOUNT_FORMATTED}  123,00€
${INPUT_COMPENSATION_PURPOSE}         Tässä on lyhyt kuvaus
${INPUT_COMPENSATION_EXPLANATION}     Selitys edellisestä avustuksesta
${INPUT_FEE_PERSON}                   6789
${INPUT_FEE_PERSON_FORMATTED}         6 789,00€
